version: '3.9'
services:
  frontend:
    build: ./front
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server/data:/app/data